services:
  # Utviklingsmiljø
  react-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Nødvendig for hot-reload i Docker
    command: npm start
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Produksjonsmiljø
  react-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  # Sikkerhetsskanning
  security-scan:
    build:
      context: .
      dockerfile: Dockerfile.security
    volumes:
      - ./:/app
    command: npm run security-check
