services:
  # Utviklingsmiljø
  react-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Nødvendig for hot-reload i Docker
    command: npm start

  # Produksjonsmiljø
  react-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
